name: movementor
description: An application that motivates you to move
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  camera: ^0.10.4
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  image: ^3.3.0
  lottie: ^2.3.2
  path_provider: ^2.0.14
  tflite_flutter: ^0.9.1
  tflite_flutter_helper:
    path: ./packages/tflite_flutter_helper

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/icon.png
    - assets/icon-app.png
    - assets/dancer-man.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-app.png"
  min_sdk_android: 21
  remove_alpha_ios: false

flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/icon.png

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/icon-app.png

    # Splash screen background color.
    color: "#ffffff"

    # App icon background color.
    icon_background_color: "#ffffff"

  web: false

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true
